### ISSUE TITLE
Please update Watopia map for the new Southern Coast Road

### ISSUE THREAD

**Issue by vangent** [andipaetzold/zwiftmap#2110]
https://zwiftinsider.com/southern-coast-expansion/

For both the zwiftmap site and the browser extension.

Thanks!

**Comment by andipaetzold** [comment]
👋 The Zwift team hasn't uploaded the map of Watopia on their website yet. Other images of Watopia (e.g. generated by stitching the tiles) either have a bad quality or are too big to be used on a website.

I pinged them (again) yesterday and will update the website as soon as possible: https://forums.zwift.com/t/outdated-watopia-map-image/585073

**Comment by vangent** [comment]
Great, thanks!

**Comment by andipaetzold** [comment]
The watopia map was updated. The chrome extension and firefox add-on was submitted and should be released soon (waiting for review)
