### ISSUE TITLE
Update to Zwift 1.68

### ISSUE THREAD

**Issue by Supercrazycoder1000** [andipaetzold/zwiftmap#2629]
The Map Image is up to date for zwift 1.68 but when I try to create a custom route on The Grade KOM or Itza KOM or one of the new routes the waypoint is placed on one of the other roads included is a screenshot with the affected area and my .GPX route
<img width="1920" alt="Screenshot 2024-06-26 at 3 35 00 PM" src="https://github.com/andipaetzold/zwiftmap/assets/91034744/0157f111-feda-4296-8fa3-d420b8682e08">
[custom-route.gpx.zip](https://github.com/user-attachments/files/15995169/custom-route.gpx.zip)

**Comment by andipaetzold** [comment]
Hey 👋 

thanks for the detailed report!

I am aware of the issue. When the update was released, I simply swapped the image, but didn't update the underlying road network. It's a boring process to get things updated and I simply didn't have enough time to do it, yet.

If you're intested, here's is the process:
1. Download the latlng stream of new routes from Strava
2. Trim these latlng streams and create edges. One edge is the road from one intersection to another
3. Create nodes/intersections and connect the edges
You can see the details of the current road layout here: https://github.com/andipaetzold/zwiftmap/tree/main/backend/src/shared/browser/roads/roads/watopia

For road surfaces it's currently also a manual process: https://github.com/andipaetzold/zwiftmap/blob/main/frontend/src/constants/worldConfigs/watopia.ts

It's probably possible to automate this, but I haven't figured out how to do that.

**Comment by andipaetzold** [comment]
The new roads are now implemented
