### ISSUE TITLE
Elevation errors in Watopia "The Grade"

### ISSUE THREAD

**Issue by oldnapalm** [andipaetzold/zwiftmap#2793]
There are gaps in the elevation profile in this area of the Watopia map (altitude drops to 14m) causing the routes passing through there to have wrong total elevation gain.

![Captura de tela 2024-09-27 175801](https://github.com/user-attachments/assets/78ea8462-e7a4-444d-9dc5-c3cf3538ee92)

![Captura de tela 2024-09-27 175928](https://github.com/user-attachments/assets/05452090-78c6-48c2-8464-ae86dc06028f)

**Comment by andipaetzold** [comment]
Thanks for reporting! Should be fixed now

**Comment by oldnapalm** [comment]
Thank you!
