### ISSUE TITLE
Strava filters links now

### ISSUE THREAD

**Issue by Glennmen** [andipaetzold/zwiftmap#2797]
It looks like Strava recently did a change that breaks the upload zwiftmap link to activity description so I guess that feature can be removed 😅 
https://communityhub.strava.com/t5/strava-features-chat/upholding-platform-safety/m-p/45352/thread-id/8013

**Comment by andipaetzold** [comment]
Meh 😞  Thanks for letting me know.

I removed/disabled the feature
